### ISSUE TITLE
Nothing happens when a user joins

### ISSUE THREAD

**Issue by Dogloverblue17** [Tomato6966/Discord-Welcome-Images#3]
I set up the bot and ran the install command, and finally noded index.js, but when someone joined the server nothing happened. The console had no errors and my config file looked like this ```{
  "TOKEN": "I put my token in here",
  "CHANNEL_WELCOME": "819672157079994398",
  "ROLES_WELCOME": ["",""]
}
```
I don't understand what is causing the issue. any idea?

**Comment by Tomato6966** [comment]
have u made sure that u enabled your privileg intents in https://discord.com/developers ? 
Like that: 
![image](https://user-images.githubusercontent.com/68145571/110854046-aa6e1f80-82b4-11eb-8936-06a6581a635f.png)

note that you just need server members intent ( the second one ) to have working welcome system.

please learn/try reading thanks!

**Comment by Dogloverblue17** [comment]
no i have not tried that, I will try it. and wow that was a  quick responce

**Comment by Tomato6966** [comment]
xD

**Comment by Dogloverblue17** [comment]
Ok thank you, that worked :D
