### ISSUE TITLE
FONT ERROR AGAIN

### ISSUE THREAD

**Issue by Puggy8893** [Tomato6966/Discord-Welcome-Images#6]
![image](https://user-images.githubusercontent.com/87098896/124929125-da5cd380-dfc5-11eb-8496-6747bf39724f.png)

Sorry. I commented on the closed issue, and i dont think i reopened so i opened this one. Anyways another error...

**Comment by Tomato6966** [comment]
This is a error from your coding not from my "module"

**Comment by Tomato6966** [comment]
Ur Font File is not readable / not right

**Comment by Puggy8893** [comment]
![image](https://user-images.githubusercontent.com/87098896/124945989-40e8ee00-dfd4-11eb-8ea4-cc15d1bc28d8.png)

**Comment by Puggy8893** [comment]
this is how i put it

**Comment by Tomato6966** [comment]
it looks right

**Comment by Tomato6966** [comment]
this is a canvas error, please ask there
